### ISSUE TITLE
Fails to compile on Linux

### ISSUE THREAD

**Issue by paines** [eriksvedang/Carp#18]
I forked your repo and managed to add some minor fixes to get it compiling under Linux including the spin demo @ https://github.com/paines/Carp/commit/fd4c1bc3168aca9b8c212dad7efc830e4a7b16da. Unfortunately I do not understand how to create a pull request !

**Comment by eriksvedang** [comment]
Oh, nice! There should be a button for it when you visit your fork of the repository here on github (you must fork and push your changes to the fork for it to work).
