### ISSUE TITLE
Readable Lisp S-expressions

### ISSUE THREAD

**Issue by sirinath** [eriksvedang/Carp#31]
Can you support Readable / Sweet syntax by @david-a-wheeler

http://readable.sourceforge.net/
http://www.dwheeler.com/readable/
http://www.dwheeler.com/readable/sweet-expressions.html

**Comment by mkfifo** [comment]
Unsure how powerful the current Carp reader macros are, but sweet looks like it could be a reader macro.

**Comment by david-a-wheeler** [comment]
Need any help?  You're certainly welcome to the posted code.

**Comment by vyp** [comment]
Wouldn't this conflict or be awkward/confusing with the curly brace dictionary literal syntax anyway?

**Comment by eriksvedang** [comment]
I'm not very keen on this at the moment as it adds complexity to the reader, and I try to keep everything as small and simple as possible.
