### ISSUE TITLE
Mkdir, touch unsafety

### ISSUE THREAD

**Issue by tomsmeding** [eriksvedang/Carp#33]
The mkdir and touch implementations in core.karp just concatenate the given name into a shell expression. Things like `(mkdir "dir; malicious_program")` will therefore not do the expected thing; this is a problem if user input is directly given to mkdir and/or touch.
I'd expect not to have to quote input when giving it to those functions.
Fix would be to use fork/execlp not sure how feasible that is from lisp?

**Comment by eriksvedang** [comment]
Yeah, those functions are not very good overall... I'll try to make safer versions

**Comment by mkfifo** [comment]
So far Carp is a reasonably thin wrapper around the c functions for those - so I would say that at this point you should be validating all user input before handing to those functions.

In general, you should be validating *all* user input before doing anything with it.

Although I also agree that Carp should do it's best to make this easy and prevent obvious attack vectors.

**Comment by tomsmeding** [comment]
Well, in C, the corresponding functions would *not* have the attack vector. That's pretty much my point.
A different example would maybe be in order:

`(mkdir "a b")`

Should this make two directories `a` and `b`, or should it make one directory `a b`? I would strongly expect the second, while the first is what happens as far as I can see.

I like the idea of Carp very much so far, and although I haven't used it yet, I'm wanting to do that in the near future. And even though I probably won't be using these functions, I wouldn't like a vulnerability à la SQL injection to be present in the very language -- think php before they understood escaping and prepared statements were a good idea.

**Comment by eriksvedang** [comment]
Yeah, agreed. Right now these commands just use system() which is also used to call the external c compiler. I just made these as handy little things to use when in the repl, to not have to turn it off to check for file output, etc. I will fix this eventually, but for now they will remain dangerous. If you wanna write a safe version of one or more of them, feel free to do so!

**Comment by mkfifo** [comment]
@tomsmeding ahh very good point about this exposing an additional set of attack vectors.

TY for the example.

My general point was that all input should be validated anyway, regardless of the safety of the underlying implementation.

However I also think we should try make them safe, if I have time I will try have a peek at this.

**Comment by mkfifo** [comment]
I have written a first attempt at addressing this, please see #37

**Comment by tomsmeding** [comment]
That looks great for safety (y)
Then the only point is that one might want to make a directory named "a b", but that's a functionality issue rather than a safety one. :)

**Comment by mkfifo** [comment]
Yeah, I was unsure what set of characters to allow exactly, so I went for a simple set that we know work safely.


I'm happy to add spaces too, although then your above example shows an issue.

So I think I will try work on a follow up that correctly quotes the string before handing it to mkdir - then we can enable spaces

The goal should be that `(mkdir "a b")` creates a single directory in the current working dir with the name "a b".

**Comment by mkfifo** [comment]
follow-up: likewise, other characters which are probably fine (e.g. `,` comes to mind) I have also excluded here for simplicity.

I think this set will grow over time.

**Comment by mkfifo** [comment]
I think this should be closed now that #43 is merged.
